# Generated by Django 3.1.2 on 2020-10-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRDApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Process_Sub_Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_sub_thread_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Process_Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_thread_name', models.CharField(max_length=100)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRDApp.process')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='process_sub_thread',
            name='process_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRDApp.process_thread'),
        ),
    ]
