# Generated by Django 3.1.2 on 2020-11-05 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRDApp', '0004_auto_20201103_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_process',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PRDApp.process'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_process_thread',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PRDApp.process_thread'),
            preserve_default=False,
        ),
    ]
